In [14]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
df['overall_pred'] = df['text_pred'] + df['audio_pred'] + df['image_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x >2 else 0)
from sklearn.metrics import confusion_matrix, classification_report

# Define label names
labels = ['Negative', 'Positive']

# Compute confusion matrix
conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

# Generate classification report
class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

# Display the confusion matrix and classification report
print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("all")

Confusion Matrix:
 [[476   3]
 [221 482]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.68      0.99      0.81       479
    Positive       0.99      0.69      0.81       703

    accuracy                           0.81      1182
   macro avg       0.84      0.84      0.81      1182
weighted avg       0.87      0.81      0.81      1182

all


In [28]:
conditions = [
    (df['overall_pred'] == 3),
    (df['overall_pred'] == 2),
    (df['overall_pred'] == 1),
    (df['overall_pred'] == 0)
]

categories = ['Positive', 'Slight Negative', 'Negative', 'Strong Negative']

# Assign the categories based on the conditions
df['voting_mechanism'] = np.select(conditions, categories, default='Uncategorized')

# Group by 'label' and 'voting_mechanism', then get value counts and percentages
grouped_data = df.groupby('label')['voting_mechanism'].value_counts(normalize=True).mul(100).round(2)

# Display the result
print(grouped_data)


label  voting_mechanism
0      Strong Negative     37.58
       Negative            34.45
       Slight Negative     27.35
       Positive             0.63
1      Positive            68.56
       Slight Negative     28.59
       Negative             2.84
Name: proportion, dtype: float64


In [29]:
df.groupby('label')['voting_mechanism'].value_counts()

label  voting_mechanism
0      Strong Negative     180
       Negative            165
       Slight Negative     131
       Positive              3
1      Positive            482
       Slight Negative     201
       Negative             20
Name: count, dtype: int64

In [37]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
# del df['Column1']
df['overall_pred'] = df['text_pred'] + df['image_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x >1 else 0)
from sklearn.metrics import confusion_matrix, classification_report

labels = ['Negative', 'Positive']


conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("image+text")

Confusion Matrix:
 [[471   8]
 [ 82 621]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.85      0.98      0.91       479
    Positive       0.99      0.88      0.93       703

    accuracy                           0.92      1182
   macro avg       0.92      0.93      0.92      1182
weighted avg       0.93      0.92      0.92      1182

image+text


In [36]:
df['label'].value_counts()

label
1    703
0    479
Name: count, dtype: int64

In [38]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
df['overall_pred'] = df['text_pred'] + df['audio_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x >1 else 0)
from sklearn.metrics import confusion_matrix, classification_report

labels = ['Negative', 'Positive']

conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("audio+text")

Confusion Matrix:
 [[352 127]
 [206 497]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.63      0.73      0.68       479
    Positive       0.80      0.71      0.75       703

    accuracy                           0.72      1182
   macro avg       0.71      0.72      0.71      1182
weighted avg       0.73      0.72      0.72      1182

audio+text


In [39]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
df['overall_pred'] = df['image_pred'] + df['audio_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x >1 else 0)
from sklearn.metrics import confusion_matrix, classification_report

labels = ['Negative', 'Positive']


conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("audio+image")

Confusion Matrix:
 [[474   5]
 [174 529]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.73      0.99      0.84       479
    Positive       0.99      0.75      0.86       703

    accuracy                           0.85      1182
   macro avg       0.86      0.87      0.85      1182
weighted avg       0.89      0.85      0.85      1182

audio+image


In [40]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
df['overall_pred'] = df['audio_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x == 1 else 0)
from sklearn.metrics import confusion_matrix, classification_report


labels = ['Negative', 'Positive']

conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("audio")

Confusion Matrix:
 [[319 154]
 [ 44 297]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.88      0.67      0.76       473
    Positive       0.66      0.87      0.75       341

    accuracy                           0.76       814
   macro avg       0.77      0.77      0.76       814
weighted avg       0.79      0.76      0.76       814

audio


In [41]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
df['overall_pred'] = df['text_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x == 1 else 0)
from sklearn.metrics import confusion_matrix, classification_report

labels = ['Negative', 'Positive']

conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("text")

Confusion Matrix:
 [[215 264]
 [ 66 637]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.77      0.45      0.57       479
    Positive       0.71      0.91      0.79       703

    accuracy                           0.72      1182
   macro avg       0.74      0.68      0.68      1182
weighted avg       0.73      0.72      0.70      1182

text


In [42]:
df = pd.read_csv('final_result.csv')
df['image_pred'] = df['predicted_mean_pool'].apply(lambda x: 0 if x == 'Negative' else 1)
del df['predicted_mean_pool']
# del df['Column1']
df['overall_pred'] = df['image_pred']
df['label'] = df['label'].apply(lambda x: 0 if x == 'Negative' else 1)
df['overall_pred_basic'] = df['overall_pred'].apply(lambda x: 1 if x == 1 else 0)
from sklearn.metrics import confusion_matrix, classification_report

labels = ['Negative', 'Positive']


conf_matrix = confusion_matrix(df['label'], df['overall_pred_basic'])

class_report = classification_report(df['label'], df['overall_pred_basic'], target_names=labels)

print("Confusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)
print("image")

Confusion Matrix:
 [[461  18]
 [ 17 686]]

Classification Report:
               precision    recall  f1-score   support

    Negative       0.96      0.96      0.96       479
    Positive       0.97      0.98      0.98       703

    accuracy                           0.97      1182
   macro avg       0.97      0.97      0.97      1182
weighted avg       0.97      0.97      0.97      1182

image


In [25]:
df[(df['label']==1)&(df['image_pred']==0)]

file  label  \
80     Tom_And_Jerry_8.0-8.5_1.mp4      1   
110      Insidious_88.0-88.5_1.mp4      1   
121  The_Conjuring_50.0-50.5_1.mp4      1   
124  Tom_And_Jerry_28.5-29.0_1.mp4      1   
157      Conjuring2_9.5-10.0_1.mp4      1   
173  Tom_And_Jerry_25.0-25.5_1.mp4      1   
230  Tom_And_Jerry_73.5-74.0_1.mp4      1   
236    The_Conjuring_5.5-6.0_1.mp4      1   
267  Tom_And_Jerry_46.5-47.0_1.mp4      1   
336       Conjuring2_9.0-9.5_1.mp4      1   
460  Tom_And_Jerry_12.0-12.5_1.mp4      1   
478  Tom_And_Jerry_47.5-48.0_1.mp4      1   
486  Tom_And_Jerry_27.0-27.5_1.mp4      1   
669  Tom_And_Jerry_69.0-69.5_1.mp4      1   
681  Tom_And_Jerry_23.0-23.5_1.mp4      1   
688         Barbie_49.5-50.0_1.mp4      1   
721    The_Conjuring_6.5-7.0_1.mp4      1   

                                                  text  text_pred  audio_pred  \
80                                     Bye. Thank you.          1           1   
110   Daddy, listen, I think it's Mommy! Josh, come...          1           0   
121                  Do you mind if I try to see Rory?          1           1   
124                         Don't sweat the technique.          1           1   
157   Get inside, both of you. Go. M-M-Margaret! Ma...          1           1   
173   Guess who's at the party? Come on, man. Have ...          1           1   
230   him alone already? Well, I got something to s...          1           1   
236   Horace, ghost hunters, paranormal researchers...          1           1   
267                                   I don't know. so          1           1   
336   I'm on tonight, cause I'm on tonight. Keith a...          1           1   
460   Now I was about to if you shut that grill let...          1           1   
478                                      Oh I'm sorry.          1           1   
486                                              Oh So          0           1   
669   We will Something right open your mouth You g...          1           1   
681   What are you doing? Oh my gosh, you scared me...          1           1   
688   What is this place? I always find, I think, b...          1           1   
721   Wow Oh, okay. Okay. Guys. Get out of here. Oh...          1           1   

     image_pred  overall_pred  overall_pred_basic  
80            0             0                   0  
110           0             0                   0  
121           0             0                   0  
124           0             0                   0  
157           0             0                   0  
173           0             0                   0  
230           0             0                   0  
236           0             0                   0  
267           0             0                   0  
336           0             0                   0  
460           0             0                   0  
478           0             0                   0  
486           0             0                   0  
669           0             0                   0  
681           0             0                   0  
688           0             0                   0  
721           0             0                   0